version: '2'

services:
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"

  app:
    restart: always
    image: kazu20/webclipboard02
    command: [/usr/src/webclipboard/start_app.sh]
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
